version: '3.8'
services:
  mongo:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    ports:
      - 27017:27017
